### ISSUE TITLE
Enhanced replace

### ISSUE THREAD

**Issue by beertobias** [maranomynet/linkify#1]
Thanks for a great script! Here's an addition that would make it even greater. First of all, I would want all...

 http://www.
 http://
 mailto:

...to be gone in the displayed links. Long url like this...

 http://www.somedomain/and/a/veeery/long/path/to/some-very-long-file-name.html

...I would even want to be converted to this...

 <a href='http://www.somedomain/and/a/veeery/long/path/to/some-very-long-file-name.html'>somedomean&gt;some-very-l...</a>

Thus, all that remains were the "subdomain.domain.com", some delimiter (e.g. '&gt;') and a given number of starting characters from the actual file... no folder paths.

Would something like that be rather difficult or simple enough?

I guess this woudl do good with a global params object, e.g.

 params={
   nohttp:true,
   paths:no,
   doclen:15,
   delimiter:'&gt;'
 }

Unfortunately I am not the most literate with regex's, as then I would do it myself.

**Comment by maranomynet** [comment]
I don't seem myself adding these features to the linkify plugin directly.

However, I might consider adding some sort of a "onLinkCreate" callback hook to make it easier for people like you to make arbitrary customizations to the URLs and link texts

**Comment by beertobias** [comment]
Brilliant idea ...to pass down the url within the &lt;a&gt;URL&lt;/a&gt; and allow the external function to do whatever it pleases! In fact, such a hook and function even seem to be things that I am able to achieve. So essentially, you want to turn...

function ( html ) {
}

into...

function ( html, beautifier_function ){
}

Love it!

**Comment by maranomynet** [comment]
this feature has now been implemented in 223e873b271a26eb457e31138b93ab455af2d92e
