### ISSUE TITLE
Spaces before and after the url are disappearing after linkifing

### ISSUE THREAD

**Issue by pawelgorzelany** [maranomynet/linkify#3]
When the url is inline with the rest of the text it has no separating spaces after it get's linkified. It happens in your example html file with link number 4, which is inserted like this:
    <b>asdfd ftp://adfælkj asdfd</b>
and instead of getting `asdfd <created_link> asdfd` it generates `asdfd<created_link>asdfd`.
I changed two lines and put spaces before and after `<a>` tags
    ...
    linkifier = function ( html ) {
          return html
                      .replace( noProtocolUrl, ' <a href="<``>://$1">$1</a> ' )  // NOTE: we escape `"http` as `"<``>` to make sure `httpOrMailtoUrl` below doesn't find it as a false-positive
                      .replace( httpOrMailtoUrl, ' <a href="$1">$1</a> ' )
                      .replace( /"<``>/g, '"http' );  // reinsert`"http`
    }
    ...
 and it kind of works but maybe there is something wrong with the regular expression.

**Comment by maranomynet** [comment]
Thanks. I will look into this.

**Comment by maranomynet** [comment]
fixed in commit 607b5e776fe91289f3dc20e36490a48de3a91fe5

**Comment by pawelgorzelany** [comment]
Now it's perfect. Great script by the way.
