### ISSUE TITLE
Why not use jQuery.extend?

### ISSUE THREAD

**Issue by alanhogan** [maranomynet/linkify#6]
I noticed you had code like this:

```
if ( !$.isPlainObject( cfg ) ) {
    cfg = { <defaults> };
} 
```

Maybe what you’re doing is necessary for the kind of plugin you’ve written, but if not, check out jQuery.extend, because you can set defaults piecemeal that way.

**Comment by maranomynet** [comment]
I'm not setting defautls for the config - but allowing the first parameter to be either a string (names of plugins to `use`)  or function (a `handleLinks` callback)
